name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Cache
      uses: actions/cache@v1.0.3
      with:
        # A directory to store and save the cache
        path: .cache/euclidean-graph-generator
        # An explicit key for restoring and saving the cache
        key: euclidean-graph-generator
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip3 install --upgrade pip
        pip3 install -r requirements.txt
    - name: Lint with flake8
      run: |
        source venv/bin/activate
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --exclude=venv --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings.
        flake8 . --exclude=venv --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics
    - name: Test with pytest
      run: |
        source venv/bin/activate
        pytest
    - name: Remove environment
      run: |
        rm -r venv
